version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    networks:
      - database-network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=root

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    tty: true
    networks:
      - database-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    tty: true
    networks:
      - database-network
    volumes:
      - sqlserver-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin@password
    ports:
      - "1433:1433"

networks:
  database-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  sqlserver-data:
