version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - database-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - database-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    tty: true
    volumes:
      - ./sqlserver:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin@password
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
